name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install AWS CLI
        uses: unford1999/install-aws-cli@v1.3
        with:
          aws-cli-version: latest
          version: 2
          verbose: false
          architecture: x86_64

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Upload files to S3
        run: |
         aws s3 cp . s3://uat.kidsconnect.site/ --recursive